[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./test-scripts/run-ts-mocha"
sim = 'bash ./stress/run_local_sim.sh'

[programs.localnet]
clearing_house = "8audUMDxGuB7hjQR3h1Fr4AhYXUd7mtpZH2MS1yaYpmn"
pyth = "2s5Aom1KJpoFesar3to6v1e562CMks1ea9TyeEe441b2"
