name: main

on: push

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
          components: rustfmt, clippy
      - name: Cargo fmt
        run: cargo fmt -- --check
  yarn-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install yarn
        run: yarn
      - name: Run prettier
        run: yarn prettify
  yarn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install yarn
        run: yarn
      - name: Run lint
        run: yarn lint
  check-for-sdk-changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      sdk: ${{ steps.filter.outputs.sdk }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            sdk:
              - 'sdk/src/**'
  release:
    runs-on: ubuntu-latest
    needs: [cargo-fmt, yarn-prettier, yarn-lint, check-for-sdk-changes]
    if: ${{ github.ref == 'refs/heads/master' && needs.changes.outputs.sdk == 'true' }}
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build sdk
        run: yarn
      - run: yarn build
      - name: Update package version
        run: npm version prerelease --preid=master
      - name: Git commit
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version);")
          git config user.name "GitHub Actions"
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -a -m "sdk: release v$VERSION"
          git push origin HEAD
      - name: Publish to npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}